# Copyright 2024 - Andrew Kwok Fai LUI and Dasun Gunasinghe
# Research Engineering Facility, Queensland University of Technology (QUT)

version: '3'

# Include Base/Default Packages
include:
    - ./docker/base-compose.yaml
    - ./robot_arms/robot-arm-compose.yaml

# Define Project Specific Services Here 
# Example: xarm_test (extending the xarm_noetic_moveit image and adds volume mounts to project specific function)
services:
    # ----- EXAMPLE IMPLEMENTATION --------
    # Rename service name as required
    xarm_test:
        # Rename the container name as required
        container_name: xarm_test
        extends:
            # DO NOT CHANGE THIS FILE PATH
            file: ./robot_arms/robot-arm-compose.yaml
            # Update the extended service depending on the type of robot you need
            # Expects <robot_type>_<ROS version>_<commander_type>
            # Where:
            #       robot_type: [xarm, panda, ur, abb]
            #       ROS version: [noetic, humble]
            #       commander_type: [moveit, armer]
            service: xarm_noetic_moveit
        # Uncomment and update the volume PATH and PACKAGE name as needed
        # volumes: 
        #     - <HOST PATH>/<PACKAGE>:/home/qcr/project_ws/src/<PACKAGE>:rw