# Copyright 2024 - Andrew Kwok Fai LUI and Dasun Gunasinghe
# Research Engineering Facility, Queensland University of Technology (QUT)

version: '3'

# Include Base/Default Packages
include:
    - base-compose.yaml
    - robot-arm-compose.yaml

# Define Project Specific Services Here 
# The .env file can be updated to bring up a defined image for use with your project
services:
    # ----- EXAMPLE IMPLEMENTATION --------
    # Rename service name as required
    robot_service:
        # Rename the container name as required
        container_name: ${ROBOT}_container
        extends:
            # DO NOT CHANGE THIS FILE PATH
            file: robot-arm-compose.yaml
            # Update the extended service depending on the type of robot you need
            # See .env
            service: ${ROBOT}_${ROSVER}_${COMMANDER}
        # Update the volume PATH and PACKAGE name as needed
        # See .env
        volumes: 
            - ${WORKSPACE_PATH}/${SCENE_PKG}:/home/qcr/project_ws/src/${SCENE_PKG}:rw
            - ${WORKSPACE_PATH}/${CONFIG_PKG}:/home/qcr/project_ws/src/${CONFIG_PKG}:rw
            - ${WORKSPACE_PATH}/${COMMANDER_PKG}:/home/qcr/project_ws/src/${COMMANDER_PKG}:rw