# Copyright 2024 - Andrew Kwok Fai LUI and Dasun Gunasinghe
# Research Engineering Facility, Queensland University of Technology (QUT)

version: '3'

# Higher-Level Definitions of Sensor Images
# This compose file defines the links to its extension and image build file
# NOTE:
#   - Each includes an extension of a derived base (largely rosbase or ros2base)
#   - Each has its own Dockerfile context for its own images (and required packages)
services:
    realsense_noetic:
        container_name: realsense_noetic
        extends:
            file: base-compose.yaml
            service: rosbase
        build:
            context: ./sensors/realsense_noetic
            dockerfile: Dockerfile
        image: realsense_noetic
        volumes:
          - /dev:/dev
        device_cgroup_rules:
          - 'c 81:* rmw'
          - 'c 189:* rmw'